export const BROKER_CATALOG = [
  { company: "IC Markets", aliases: [] },
  { company: "Pepperstone", aliases: [] },
  { company: "Exness", aliases: [] },
  { company: "XM", aliases: [] },
  { company: "FP Markets", aliases: [] },
  { company: "Tickmill", aliases: [] },
  { company: "BlackBull Markets", aliases: [] },
  { company: "Vantage", aliases: [] },
  { company: "FxPro", aliases: [] },
  { company: "HFM", aliases: [] },
  { company: "Octa", aliases: [] },
  { company: "Eightcap", aliases: [] },
  { company: "OANDA", aliases: [] },
  { company: "FOREX.com", aliases: [] },
  { company: "IG", aliases: [] },
  { company: "AvaTrade", aliases: [] },
  { company: "Admiral Markets", aliases: [] },
  { company: "Axi", aliases: [] },
  { company: "Axiory", aliases: [] },
  { company: "ActivTrades", aliases: [] },
  { company: "Alpari", aliases: [] },
  { company: "ATC Brokers", aliases: [] },
  { company: "BDSwiss", aliases: [] },
  { company: "Blueberry Markets", aliases: [] },
  { company: "Capital.com", aliases: [] },
  { company: "CMC Markets", aliases: [] },
  { company: "Darwinex", aliases: [] },
  { company: "Dukascopy", aliases: [] },
  { company: "EasyMarkets", aliases: [] },
  { company: "Ebury", aliases: [] },
  { company: "eToro", aliases: [] },
  { company: "FBS", aliases: [] },
  { company: "FXTM", aliases: [] },
  { company: "FXCM", aliases: [] },
  { company: "FXOpen", aliases: [] },
  { company: "FXPrimus", aliases: [] },
  { company: "GBE brokers", aliases: [] },
  { company: "Global Prime", aliases: [] },
  { company: "GO Markets", aliases: [] },
  { company: "Hantec Markets", aliases: [] },
  { company: "HotForex", aliases: [] },
  { company: "HYCM", aliases: [] },
  { company: "ICM Trader", aliases: [] },
  { company: "InstaForex", aliases: [] },
  { company: "Interactive Brokers", aliases: [] },
  { company: "IronFX", aliases: [] },
  { company: "Just2Trade", aliases: [] },
  { company: "Libertex", aliases: [] },
  { company: "LiteFinance", aliases: [] },
  { company: "LMAX", aliases: [] },
  { company: "Markets.com", aliases: [] },
  { company: "MEX Atlantic", aliases: [] },
  { company: "Moneta Markets", aliases: [] },
  { company: "MultiBank Group", aliases: [] },
  { company: "NordFX", aliases: [] },
  { company: "NPBFX", aliases: [] },
  { company: "Optimus Futures", aliases: [] },
  { company: "Orbex", aliases: [] },
  { company: "Plus500", aliases: [] },
  { company: "PuPrime", aliases: [] },
  { company: "RoboForex", aliases: [] },
  { company: "Saxo Bank", aliases: [] },
  { company: "Spreadex", aliases: [] },
  { company: "Swissquote", aliases: [] },
  { company: "ThinkMarkets", aliases: [] },
  { company: "TMGM", aliases: [] },
  { company: "Trade Nation", aliases: [] },
  { company: "Tradeview Markets", aliases: [] },
  { company: "Trading 212", aliases: [] },
  { company: "Trireme Capital", aliases: [] },
  { company: "Union Markets", aliases: [] },
  { company: "Velocity Trade", aliases: [] },
  { company: "VT Markets", aliases: [] },
  { company: "Windsor Brokers", aliases: [] },
  { company: "XTB", aliases: [] },
  { company: "ZuluTrade", aliases: [] },
  { company: "Fusion Markets", aliases: [] },
  { company: "Raw Trading Ltd", aliases: [] },
  { company: "Skilling", aliases: [] },
  { company: "StarTrader", aliases: [] },
  { company: "AcerTrade", aliases: [] },
  { company: "AMarkets", aliases: [] },
  { company: "AETOS", aliases: [] },
  { company: "AFX Group", aliases: [] },
  { company: "Anzo Capital", aliases: [] },
  { company: "Aron Groups", aliases: [] },
  { company: "Aspire Forex", aliases: [] },
  { company: "Ava Options", aliases: [] },
  { company: "Baxia Markets", aliases: [] },
  { company: "Big Markets", aliases: [] },
  { company: "Bonds.com", aliases: [] },
  { company: "Broker Direct", aliases: [] },
  { company: "Bullwaves", aliases: [] },
  { company: "CFI Financial", aliases: [] },
  { company: "City Index", aliases: [] },
  { company: "ClickTrades", aliases: [] },
  { company: "Core Spreads", aliases: [] },
  { company: "Deriv", aliases: [] },
  { company: "DoTrading", aliases: [] },
  { company: "Earn Markets", aliases: [] },
  { company: "EC Markets", aliases: [] },
  { company: "Equiti", aliases: [] },
  { company: "Errante", aliases: [] },
  { company: "Eurotrader", aliases: [] },
  { company: "eXcentral", aliases: [] },
  { company: "Finam", aliases: [] },
  { company: "Fincorp", aliases: [] },
  { company: "FXTM Invest", aliases: [] },
  { company: "Gala Markets", aliases: [] },
  { company: "GC Money", aliases: [] },
  { company: "Golden Brokers", aliases: [] },
  { company: "Grand Capital", aliases: [] },
  { company: "GTCM", aliases: [] },
  { company: "HF Markets", aliases: [] },
  { company: "iCFD", aliases: [] },
  { company: "ICM Capital", aliases: [] },
  { company: "IFC Markets", aliases: [] },
  { company: "iFOREX", aliases: [] },
  { company: "Invast Global", aliases: [] },
  { company: "InvestAZ", aliases: [] },
  { company: "JustMarkets", aliases: [] },
  { company: "Key to Markets", aliases: [] },
  { company: "Land-FX", aliases: [] },
  { company: "LegacyFX", aliases: [] },
  { company: "Leverate", aliases: [] },
  { company: "LiquidityX", aliases: [] },
  { company: "Lirunex", aliases: [] },
  { company: "LQD Markets", aliases: [] },
  { company: "M4Markets", aliases: [] },
  { company: "MaxiMarkets", aliases: [] },
  { company: "MetaQuotes Demo", aliases: [] },
  { company: "MFX Broker", aliases: [] },
  { company: "MTrading", aliases: [] },
  { company: "NAGA", aliases: [] },
  { company: "NAGA Markets", aliases: [] },
  { company: "NestTrade", aliases: [] },
  { company: "NSBroker", aliases: [] },
  { company: "One Financial Markets", aliases: [] },
  { company: "Pacific Union", aliases: [] },
  { company: "PaxForex", aliases: [] },
  { company: "PHAT Markets", aliases: [] },
  { company: "Pocket Option", aliases: [] },
  { company: "PrimeXBT", aliases: [] },
  { company: "Profit Trading", aliases: [] },
  { company: "Purple Trading", aliases: [] },
  { company: "Quotex", aliases: [] },
  { company: "RannForex", aliases: [] },
  { company: "Refresh Markets", aliases: [] },
  { company: "Rivkin Securities", aliases: [] },
  { company: "Royal Financial Trading", aliases: [] },
  { company: "Safi Markets", aliases: [] },
  { company: "Sapa Markets", aliases: [] },
  { company: "Scope Markets", aliases: [] },
  { company: "SimpleFX", aliases: [] },
  { company: "Smart Markets", aliases: [] },
  { company: "ST Market", aliases: [] },
  { company: "Storm Markets", aliases: [] },
  { company: "Svenska Handelsbanken", aliases: [] },
  { company: "Switch Markets", aliases: [] },
  { company: "Taurex", aliases: [] },
  { company: "T4Trade", aliases: [] },
  { company: "The Forex Market", aliases: [] },
  { company: "TickTrader", aliases: [] },
  { company: "Titans Forex", aliases: [] },
  { company: "Trade Capital Markets", aliases: [] },
  { company: "Tradeo", aliases: [] },
  { company: "Tradivex", aliases: [] },
  { company: "TriumphFX", aliases: [] },
  { company: "TruTrade", aliases: [] },
  { company: "UFX", aliases: [] },
  { company: "Vantage International", aliases: [] },
  { company: "Vantage Global", aliases: [] },
  { company: "Vibon Markets", aliases: [] },
  { company: "Vision Trade", aliases: [] },
  { company: "VTB Forex", aliases: [] },
  { company: "Whitelabel Brokers", aliases: [] },
  { company: "XTB Online Trading", aliases: [] },
  { company: "Yapikredi Invest", aliases: [] },
  { company: "Yes Traders", aliases: [] },
  { company: "Z.com Trade", aliases: [] },
  { company: "ZBIFX", aliases: [] },
  { company: "ZFX", aliases: [] },
  { company: "AAAFx", aliases: [] },
  { company: "ACY Securities", aliases: [] },
  { company: "AETOS Capital Group", aliases: [] },
  { company: "Alfa Forex", aliases: [] },
  { company: "Alpari International", aliases: [] },
  { company: "Askap Futures", aliases: [] },
  { company: "ATFX", aliases: [] },
  { company: "AvaTradeEU", aliases: [] },
  { company: "AXSTrade", aliases: [] },
  { company: "Baxia", aliases: [] },
  { company: "BCS Forex", aliases: [] },
  { company: "Binance Futures", aliases: [] },
  { company: "BIT Markets", aliases: [] },
  { company: "BlackWell Global", aliases: [] },
  { company: "BrokerCreditService", aliases: [] },
  { company: "Bybit", aliases: [] },
  { company: "Capital Bear", aliases: [] },
  { company: "Capitals.com", aliases: [] },
  { company: "CFD Capital", aliases: [] },
  { company: "CMS Prime", aliases: [] },
  { company: "Colmex Pro", aliases: [] },
  { company: "CyberTrade", aliases: [] },
  { company: "DCI Capital", aliases: [] },
  { company: "Doto Brokers", aliases: [] },
  { company: "Ducascopy Bank", aliases: [] },
  { company: "EBC Financial Group", aliases: [] },
  { company: "EFX Group", aliases: [] },
  { company: "Elite Trader Funding", aliases: [] },
  { company: "EverFX", aliases: [] },
  { company: "Evo Markets", aliases: [] },
  { company: "Exclusive Markets", aliases: [] },
  { company: "FINAM Forex", aliases: [] },
  { company: "FirewoodFX", aliases: [] },
  { company: "Forex4you", aliases: [] },
  { company: "ForexChief", aliases: [] },
  { company: "Forex.com UK", aliases: [] },
  { company: "ForexTime", aliases: [] },
  { company: "Fortune Prime Global", aliases: [] },
  { company: "FreshForex", aliases: [] },
  { company: "FTMO", aliases: [] },
  { company: "FXTM Global", aliases: [] },
  { company: "GCEX", aliases: [] },
  { company: "GDMFX", aliases: [] },
  { company: "Gembell Limited", aliases: [] },
  { company: "Global Futures", aliases: [] },
  { company: "GMI Markets", aliases: [] },
  { company: "Goldenburg Capital", aliases: [] },
  { company: "GTCFX", aliases: [] },
  { company: "Guggenheim Markets", aliases: [] },
  { company: "Hantec Markets UK", aliases: [] },
  { company: "HF Markets Global", aliases: [] },
  { company: "HFM Global", aliases: [] },
  { company: "Holi Capital", aliases: [] },
  { company: "HotForex Global", aliases: [] },
  { company: "HY Markets", aliases: [] },
  { company: "IC Brokers", aliases: [] },
  { company: "IC Markets Global", aliases: [] },
  { company: "IC Markets EU", aliases: [] },
  { company: "IC Markets AU", aliases: [] },
  { company: "ICM Brokers", aliases: [] },
  { company: "Icon FX", aliases: [] },
  { company: "IFC Markets Global", aliases: [] },
  { company: "IG Index", aliases: [] },
  { company: "IG Markets", aliases: [] },
  { company: "InstaForex Europe", aliases: [] },
  { company: "IronFX Global", aliases: [] },
  { company: "iTrade Global", aliases: [] },
  { company: "Just2Trade Global", aliases: [] },
  { company: "JustMarkets Global", aliases: [] },
  { company: "Key Trading", aliases: [] },
  { company: "Kraken Futures", aliases: [] },
  { company: "KVB Markets", aliases: [] },
  { company: "KVB Kunlun", aliases: [] },
  { company: "LCG", aliases: [] },
  { company: "Libertex Global", aliases: [] },
  { company: "LiteFinance Global", aliases: [] },
  { company: "LMAX Exchange", aliases: [] },
  { company: "LMAX Global", aliases: [] },
  { company: "LMAX Digital", aliases: [] },
  { company: "London Capital Group", aliases: [] },
  { company: "Magic Trading", aliases: [] },
  { company: "Market.com", aliases: [] },
  { company: "Markets.com UK", aliases: [] },
  { company: "Maxi Markets", aliases: [] },
  { company: "MEX Group", aliases: [] },
  { company: "MTrading Global", aliases: [] },
  { company: "MultiBank FX", aliases: [] },
  { company: "NAGA Trader", aliases: [] },
  { company: "NordFX Global", aliases: [] },
  { company: "NPBFX Global", aliases: [] },
  { company: "OANDA Global Markets", aliases: [] },
  { company: "OANDA Europe", aliases: [] },
  { company: "OANDA Asia Pacific", aliases: [] },
  { company: "OctaFX", aliases: ["octa", "octa fx"] },
  { company: "Octa Markets", aliases: [] },
  { company: "Octa Markets Global", aliases: [] },
  { company: "OneRoyal", aliases: [] },
  { company: "Optimus", aliases: [] },
  { company: "Orbex Global", aliases: [] },
  { company: "Pepperstone Global", aliases: [] },
  { company: "Pepperstone AU", aliases: [] },
  { company: "Pepperstone UK", aliases: [] },
  { company: "Pepperstone EU", aliases: [] },
  { company: "PhillipCapital", aliases: [] },
  { company: "Plus500CY", aliases: [] },
  { company: "Prime Trading", aliases: [] },
  { company: "PuPrime Global", aliases: [] },
  { company: "RoboForex EU", aliases: [] },
  { company: "RoboForex Global", aliases: [] },
  { company: "Royal Markets", aliases: [] },
  { company: "Saxo Markets", aliases: [] },
  { company: "Scope Markets Global", aliases: [] },
  { company: "Skilling Markets", aliases: [] },
  { company: "StarTrader Global", aliases: [] },
  { company: "Swissquote Bank", aliases: [] },
  { company: "ThinkMarkets Global", aliases: [] },
  { company: "Tickmill Europe", aliases: [] },
  { company: "Tickmill UK", aliases: [] },
  { company: "Tickmill Global", aliases: [] },
  { company: "TMGM Global", aliases: [] },
  { company: "Trade360", aliases: [] },
  { company: "Trade Nation Global", aliases: [] },
  { company: "Tradeview", aliases: [] },
  { company: "Trireme", aliases: [] },
  { company: "Umarkets", aliases: [] },
  { company: "Union Markets Global", aliases: [] },
  { company: "Vantage Markets", aliases: [] },
  { company: "Vantage FX", aliases: [] },
  { company: "VT Markets Global", aliases: [] },
  { company: "Windsor Brokers Global", aliases: [] },
  { company: "XM Global", aliases: [] },
  { company: "XM Trading", aliases: [] },
  { company: "XM.com", aliases: [] },
  { company: "XTB Limited", aliases: [] },
  { company: "XTB Africa", aliases: [] },
  { company: "YesTrader", aliases: [] },
  { company: "Z.com Forex", aliases: [] },
  { company: "Razor Markets", aliases: ["razor", "razormarkets", "razor markets sa", "razor mt5"] },
  { company: "GT247", aliases: [] },
  { company: "GT247.com", aliases: ["gt247", "gt 247"] },
  { company: "EasyTrader", aliases: [] },
  { company: "EasyEquities", aliases: [] },
  { company: "RocketX", aliases: [] },
  { company: "CapX Markets", aliases: [] },
  { company: "CMC Markets South Africa", aliases: ["cmc sa", "cmc markets sa"] },
  { company: "IG South Africa", aliases: ["ig sa", "ig markets sa"] },
  { company: "Saxo Capital Markets South Africa", aliases: [] },
  { company: "Swissquote South Africa", aliases: [] },
  { company: "OANDA South Africa", aliases: [] },
  { company: "Interactive Brokers South Africa", aliases: [] },
  { company: "Plus500 South Africa", aliases: [] },
  { company: "eToro South Africa", aliases: [] },
  { company: "Trading 212 South Africa", aliases: [] },
  { company: "XTB South Africa", aliases: ["xtb sa", "xtb africa"] },
  { company: "Markets.com South Africa", aliases: [] },
  { company: "City Index South Africa", aliases: [] },
  { company: "Admirals South Africa", aliases: [] },
  { company: "Admiral Markets South Africa", aliases: [] },
  { company: "ThinkMarkets South Africa", aliases: [] },
  { company: "Pepperstone South Africa", aliases: ["pepperstone sa"] },
  { company: "IC Markets South Africa", aliases: ["ic markets sa", "icmarkets"] },
  { company: "Exness South Africa", aliases: ["exness sa", "exness africa"] },
  { company: "XM South Africa", aliases: ["xm sa", "xm africa"] },
  { company: "HFM South Africa", aliases: ["hfm", "hotforex", "hf markets"] },
  { company: "HF Markets South Africa", aliases: ["hfm", "hotforex"] },
  { company: "AvaTrade South Africa", aliases: [] },
  { company: "Tickmill South Africa", aliases: [] },
  { company: "Vantage South Africa", aliases: [] },
  { company: "FP Markets South Africa", aliases: [] },
  { company: "Blueberry Markets South Africa", aliases: [] },
  { company: "Fusion Markets South Africa", aliases: [] },
  { company: "GO Markets South Africa", aliases: [] },
  { company: "Global Prime South Africa", aliases: [] },
  { company: "Axi South Africa", aliases: [] },
  { company: "BlackBull Markets South Africa", aliases: [] },
  { company: "OctaFX", aliases: ["octa", "octa fx"] },
  { company: "JustMarkets", aliases: [] },
  { company: "JustForex", aliases: [] },
  { company: "FXPesa", aliases: [] },
  { company: "Accuindex", aliases: [] },
  { company: "SafeTrade", aliases: [] },
  { company: "Safe Markets", aliases: [] },
  { company: "AfrAsia Securities", aliases: [] },
  { company: "Standard Bank Online Trading", aliases: [] },
  { company: "Investec Share Trading", aliases: [] },
  { company: "PSG Wealth", aliases: [] },
  { company: "SatrixNOW", aliases: [] },
  { company: "Purple Group", aliases: [] },
  { company: "Velocity Trade South Africa", aliases: ["velocity", "velocitytrade"] },
  { company: "FundedNext", aliases: [] },
  { company: "The Funded Trader", aliases: [] },
  { company: "FTMO", aliases: [] },
  { company: "Fidelcrest", aliases: [] },
  { company: "SurgeTrader", aliases: [] },
  { company: "E8 Funding", aliases: [] },
  { company: "Topstep", aliases: [] },
  { company: "My Forex Funds", aliases: [] },
  { company: "DNA Funded", aliases: [] },
  { company: "FundingPips", aliases: [] },
  { company: "Instant Funding", aliases: [] },
  { company: "Maven Trading", aliases: [] },
  { company: "Prop Firm Match", aliases: [] },
];

export function searchLocalBrokers(query, platform = "MT5") {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return [];
  const matches = BROKER_CATALOG.filter((b) => {
    const hay = [b.company, ...(b.aliases || [])].join(" ").toLowerCase();
    return hay.includes(q) || q.split(/\s+/).every((p) => hay.includes(p));
  }).slice(0, 40);
  return matches.map((b, index) => ({
    id: `local::${b.company}::${index}`,
    company: b.company,
    name: b.company,
    site: "",
    logoUrl: "",
    access: [],
    platform,
    custom: false,
    local: true,
  }));
}
